spring.application.name=chatroom-server

# neon db - blabber_ChatRoom
spring.datasource.url=jdbc:postgresql://ep-sparkling-union-a1muow3p-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_uaVFhwtbXH28
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
jwt.secret=blabberChatRoomSecretKey1234567890blabberChatRoom
jwt.expiration=86400000

# Server
server.port=8080

